import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          formButtonPrimary:
            "bg-primary hover:bg-primary/90 border-none py-2 shadow-none ring-0 outline-none text-sm normal-case",
        }
      }}

    >
      <html lang="en">
        <body className={`${inter.className} min-h-screen`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
